### ISSUE TITLE
iLO 5 Create Logical Drive with Redfish doesn't take effect after reboot

### ISSUE THREAD

**Issue by 4b8f8d4c4767adaf59c70bd9d5b376cc** [HewlettPackard/python-ilorest-library#27]
Hello,

iLO 5 Create Logical Drive with Redfish doesn't take effect after reboot

```
{
    "LogicalDrives": [
       {
          "CapacityGiB": 960,
          "Raid": "Raid0",
          "StripSizeBytes": 262144,
          "LogicalDriveName": "MyLD",
          "DataDrives": [
                "1I:1:1",
                "1I:1:2"
          ],
          "SpareDrives": [
                "1I:1:3"
          ],
          "Accelerator": "ControllerCache" 
       }
    ]
}

/redfish/v1/systems/1/smartstorageconfig/settings/ 
```

Return : 

```
HTTP/1.1 200 OK
< Cache-Control: no-cache
< Content-type: application/json; charset=utf-8
< Date: Mon, 26 Mar 2018 11:21:58 GMT
< ETag: W/"9605591E"
< OData-Version: 4.0
< Transfer-Encoding: chunked
< X-Frame-Options: sameorigin
< X_HP-CHRP-Service-Version: 1.0.3
<
* Curl_http_done: called premature == 0
* Connection #0 to host left intact
{"error":{"@Message.ExtendedInfo":[{"MessageId":"Base.1.0.Success"}],"code":"iLO.0.10.ExtendedInfo","message":"See @Message.ExtendedInfo for more information."}}        
```

After reboot, nothing...

**Comment by Yergidy** [comment]
Since it takes a system reboot to attempt to apply smartstorage settings, even if it returns an 200 Success when initially performing the PUT some issue may prevent the settings from taking affect after a reboot. You can see what error is stopping the changes by looking at the Messages list here: /redfish/v1/systems/1/smartstorageconfig/ after reboot. These error messages coincide with the error strings here: /redfish/v1/registrystore/registries/en/smartstoragemessages.v2_0_0.smartstoragemessages/ for a string message response.

**Comment by Yergidy** [comment]
Since it takes a system reboot to attempt to apply smartstorage settings, even if it returns an 200 Success when initially performing the PUT some issue may prevent the settings from taking affect after a reboot. You can see what error is stopping the changes by looking at the Messages list here: /redfish/v1/systems/1/smartstorageconfig/ after reboot. These error messages coincide with the error strings here: /redfish/v1/registrystore/registries/en/smartstoragemessages.v2_0_0.smartstoragemessages/ for a string message response.

**Comment by 4b8f8d4c4767adaf59c70bd9d5b376cc** [comment]
Hello, 

Thanks, error is 

"Messages":[

    {
        "MessageArgs":[
            "PhysicalDrives"
        ],
        "MessageId":"SmartStorageMessages.2.0.0.PropertyKeyMissing",
        "RelatedProperties":[
            "#/PhysicalDrives"
        ]
    },
    {
        "MessageId":"SmartStorageMessages.2.0.0.Success"
    }

],

I took an example of a reference API ...


request : 

{
    "LogicalDrives": [
       {
          "CapacityGiB": 558,
          "Raid": "Raid0",
          "StripSizeBytes": 262144,
          "LogicalDriveName": "MyLD",
          "DataDrives": [
                "1I:1:1",
                "1I:1:2"
          ],
          "Accelerator": "ControllerCache" 
       }
    ],
    "DataGuard": "Disabled"
}

**Comment by 4b8f8d4c4767adaf59c70bd9d5b376cc** [comment]
Hello, 

Thanks, error is 

"Messages":[

    {
        "MessageArgs":[
            "PhysicalDrives"
        ],
        "MessageId":"SmartStorageMessages.2.0.0.PropertyKeyMissing",
        "RelatedProperties":[
            "#/PhysicalDrives"
        ]
    },
    {
        "MessageId":"SmartStorageMessages.2.0.0.Success"
    }

],

I took an example of a reference API ...


request : 

{
    "LogicalDrives": [
       {
          "CapacityGiB": 558,
          "Raid": "Raid0",
          "StripSizeBytes": 262144,
          "LogicalDriveName": "MyLD",
          "DataDrives": [
                "1I:1:1",
                "1I:1:2"
          ],
          "Accelerator": "ControllerCache" 
       }
    ],
    "DataGuard": "Disabled"
}
